TechStaffApp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

inventory/urls.py
from django.urls import path
from . import views
from django.conf.urls import include
from django.views.generic.base import RedirectView

app_name = 'inventory'

urlpatterns = [
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('', RedirectView.as_view(url='http://localhost:8000/login/'), name='login-redirect'),
    path('home/', views.home_view, name='home'),
    path('home/DNS_Form/', views.dns_view, name='dns'),
    path('admin/auth/admin_view', views.admin_view, name='admin'),
    path('ipdashboard/', views.IPDash, name="ipdashboard"),
    path('ajax/buildings/', views.getBuilding, name = 'get_building'),
    path('ajax/ipv6/', views.getBuilding, name = 'get_building'),
    path('itemdetails/<int:item_id>/', views.itemdetails_view, name='itemdetails'),
    path('itemdetails/<int:item_id>/delete/', views.item_delete, name='item_delete'),
    path('addequipment/', views.addequipment_view, name='addequipment'),
    path('homeuseform/', views.homeuseform_view, name='homeuseform'),
    path('networkform/', views.networkform_view, name='networkform'),
    path('searchqueryform/', views.searchqueryform_view, name='searchqueryform'),
    path('IPv4/<int:b_name>/<int:item_id>', views.gen_ipv4, name='ipv4'),
    path('IPv6/<int:b_name>/<int:item_id>', views.gen_ipv6, name='ipv6'),
    path('itemdetails/<int:item_id>/apply_changes/', views.apply_changes, name='apply_changes'),
    path('itemdetails/<int:item_id>/checkout_form/', views.checkout_form, name='checkout_form'),
    path('checkedequipment/', views.user_home, name='checked_equipment'),
]

techstaff/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('inventory.urls', namespace="inventory"))
]

inventory/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone
# Create your models here.

class InventoryUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="User")
    phone_number = models.CharField(max_length=20, blank=True, null=True, verbose_name="Phone number")
    pid = models.CharField(max_length=255, blank=True, null=True, verbose_name="PID")
    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

class Building(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True, verbose_name="Building")
    ipv6_prefix = models.CharField(max_length=255, blank=True, null=True, verbose_name="IPv6 prefix")
    def __str__(self):
        return self.name

class IP(models.Model):
    IPv4='IPv4'
    IPv6='IPv6'
    ip_types = [
        (IPv4, "IPv4"),
        (IPv6, "IPv6"),
    ]
    building = models.ForeignKey(Building, on_delete=models.RESTRICT, blank=True, verbose_name="Building")
    ip_type = models.CharField(choices=ip_types, max_length=5, default=IPv4, verbose_name="IP type")
    address = models.CharField(max_length=40, blank=True, verbose_name="Address")
    date = models.DateField(auto_now_add=True, blank=True, verbose_name="Date")
    in_use = models.BooleanField(verbose_name="In use")
    def __str__(self):
        return self.address


class Hostname(models.Model):
    hostname = models.CharField(max_length=255, verbose_name="Hostname")
    building = models.ForeignKey(Building, on_delete=models.RESTRICT, blank=True, verbose_name="Building")
    aliases = models.CharField(max_length=255, blank=True, verbose_name="Aliases")
    ipv4 = models.ForeignKey(IP, on_delete=models.SET_NULL, null=True, blank=True, related_name="HostnameIPv4", verbose_name="IPv4")
    ipv6 = models.ForeignKey(IP, on_delete=models.SET_NULL, null=True, blank=True, related_name="HostnameIPv6", verbose_name="IPv6")
    in_use = models.BooleanField(verbose_name="In Use")
    def __str__(self):
        return self.hostname

class Equipment(models.Model):
    vt_tag = models.CharField(max_length=255, blank=True, null=True, verbose_name="VT tag")
    building = models.ForeignKey(Building, blank=True, null=True, on_delete=models.RESTRICT, verbose_name="Building")
    room = models.CharField(max_length=15, blank=True, null=True, verbose_name="Room")
    manufacturer_model = models.CharField(max_length=255, blank=True, null=True, verbose_name="Manufacturer/Model")
    serial_number = models.CharField(max_length=255, blank=True, null=True, verbose_name="Serial number")
    description = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Description")
    classification =  models.CharField(max_length=255, blank=True, null=True, verbose_name="Classification")
    custodian = models.CharField(max_length=255, blank=True, null=True, verbose_name="Custodian")
    purchase_order = models.CharField(max_length=255, blank=True, null=True, verbose_name="Purchase order")
    purchase_date = models.DateField(blank=True, null=True, verbose_name="Purchase date")
    purchase_value = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True, verbose_name="Purchase value")
    acquisition_date = models.DateField(blank=True, null=True, verbose_name="Acquisition date")
    hostname = models.ForeignKey(Hostname, on_delete=models.RESTRICT, blank=True, null=True, related_name="Hostname", verbose_name="Hostname")
    dept = models.CharField(max_length=10, blank=True, verbose_name="Department")
    status = models.CharField(max_length=128, blank=True, verbose_name="Status")
    mail_exchange = models.ForeignKey(Hostname, on_delete=models.RESTRICT, blank=True, null=True, related_name="MailExchangeHostname", verbose_name="Mail exchange")
    #have to change mail exchange to hostname 
    cs_tag = models.CharField(max_length=255, blank=True, null=True, verbose_name="CS tag")
    notes = models.CharField(max_length=10000, blank=True, null=True, verbose_name="Notes")

class Checkout(models.Model):
    contact = models.ForeignKey(InventoryUser, on_delete=models.RESTRICT, blank=True, verbose_name="Contact")
    equipment = models.ForeignKey(Equipment, on_delete=models.RESTRICT, blank=True, verbose_name="Equipment")
    checkoutdate = models.DateField(blank=True, auto_now_add=True, verbose_name="Checkout date")

class History(models.Model):
    command = models.CharField(max_length=255, blank=True, verbose_name="Command")
    execution_time = models.TimeField(auto_now_add=True, blank=True, verbose_name="Execution time")
    executor = models.EmailField(max_length=255, blank=True, verbose_name="Executor") 
    equipment = models.ForeignKey(Equipment, on_delete=models.RESTRICT, blank=True, verbose_name="Equipment")

inventory/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import Permission, User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import *
from django.db.models import Q
from django.contrib.auth.models import User
from rest_framework.generics import ListAPIView
from .serializers import IPSerializers, BuildingSerializers, HostnameSerializers
import csv

from django.http import HttpResponse
from .forms import EquipmentForm

import re
from django import forms
from django.http import HttpResponse, JsonResponse
from .forms import EquipmentForm, HostnameForm, BuildingForm, IPRangeForm, IPv6Form
from django.core import serializers
from django.contrib import messages


from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .forms import *
from django.core import serializers
from django.contrib import messages
from django.forms import formset_factory



import random

# Create your views here.
@login_required
def home_view(request):
    # Handles search query
    context = {}
    if request.user.is_superuser:
        context['equipments'] = Equipment.objects.all()
    else: # if request.user.is_staff
        user = User.objects.get(id=request.user.id)
        inventory_user = InventoryUser.objects.get(user=user)
        print(inventory_user)
        checkouts = Checkout.objects.filter(contact=inventory_user)
        context['equipments'] = []
        for c in checkouts:
            context['equipments'].append(Equipment.objects.get(id=c.equipment.id))
        print(context['equipments'])
    return render(request, 'inventory/home.html', context)

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/home')
        if user is None:
            messages.error(request, "Either password/username is incorrect. Please try again!")
    return render(request, 'inventory/login.html')

def user_home(request):
    context = {
        'equipments': Equipment.objects.all()
    }
    return render(request, 'inventory/userCheckedEquipment.html', context)

def logout_view(request):
    logout(request)
    return redirect('/login')

def getHexVals():
    hexVals = ['0', '1','2', '3', '4', '5', '6', '7','8', '9', 'A', 'B', 'C', 'D', 'E', 'F']
    initial = ""
    for x in range(0, 5):
        final = ":"
        for x in range(0, 4):
            index = random.randint(0, 15)
            char = hexVals[index]
            final = final + char
        initial = initial + final
    print(initial)
    return initial



def gen_ipv6(request, b_name, item_id):
    building = Building.objects.filter(id=b_name)
    if len(building) == 0:
        messages.info(request, "No Building prefix found")
    else:
        ipv6 = IP()
        ipv6.building = building[0]
        ipv6.ip_type = "I6"
        ipv6.in_use = True
        address = building[0].ipv6_prefix + getHexVals()
        print(address)
        ipv6.address = address
        ipv6.save()
        equip = Equipment.objects.get(id=item_id)
        if equip.hostname:
            print("Hostname specified %s" % equip.hostname.hostname)
            equip.hostname.ipv6 = ipv6
            #equip.hostname.ipv6.save()
            equip.hostname.save()
            print(equip.hostname.ipv6.address)
            # create new command stamp
            newCommand = History()
            newCommand.command = "IPv6 created"
            executor = '%s@vt.edu' % equip.custodian
            print(executor)
            newCommand.executor = executor
            newCommand.equipment = equip
            newCommand.save()
        else:
            print("No hostname specified")
            messages.info(request, "No hostname specified")
    print("Ypu are in IPv6")

    return redirect('/itemdetails/%i/' % item_id)

@login_required
def checkout_form(request, item_id):
    equip = Equipment.objects.get(id=item_id)
    name = request.POST.get('name', '').strip()
    office = request.POST.get('office', '').strip()
    email = request.POST.get('email', '').strip()
    phone = request.POST.get('phone', '').strip()
    firstNameFac = request.POST.get('firstNameFac', '').strip()
    lastNameFac = request.POST.get('lastNameFac', '').strip()
    emailFac = request.POST.get('emailFac', '').strip()
    phoneFac = request.POST.get('phoneFac', '').strip()
    pidFac = request.POST.get('pidFac', '').strip()

    checked = Checkout()
    checked.equipment = equip
    inventoryUser = InventoryUser.objects.filter(pid=pidFac)
    #there is an inverntory user already 
    if len(inventoryUser) > 0:
        checked.contact = inventoryUser[0]
        checked.save()
    else:
        # need to create a new Inventory User
        newInven = InventoryUser()
        newInven.phone_number = phoneFac
        newInven.pid = pidFac
        getUser = User.objects.filter(email=emailFac)
        if len(getUser) > 0:
            # there is a user in the system 
            newInven.user = getUser[0]
            newInven.save()
            checked.contact = newInven
            checked.save()
        else:
            # create a new user username is email and password is pid
            user = User.objects.create_user(username=emailFac, email=emailFac, password=pidFac)
            user.first_name = firstNameFac
            user.last_name = lastNameFac
            #user.last_name 
            user.save()
            newInven.user = user 
            newInven.user.save()
            newInven.save()
            checked.contact = newInven
            checked.save()
        # checked.save()
    context = {'name':name, 'office':office, 'email':email, 'phone':phone, 'equip': equip, 'checked':checked}
    return render(request, 'inventory/checkout.html', context)


@login_required
def apply_changes(request, item_id):
    equip = Equipment.objects.get(id=item_id)
    CSTag = request.POST.get('cstag','').strip()
    Notes = request.POST.get('notes','').strip()
    VTTag = request.POST.get('vttag','').strip()
    Description = request.POST.get('desc','').strip()
    HostedName = request.POST.get('host', '').strip()
    Alias = request.POST.get('alias', '').strip()
    # Dropdown can be used for dropdown menu in classification
    Room = request.POST.get('room', '').strip()
    Status = request.POST.get('status', '').strip()
    SerialNum = request.POST.get('serial', '').strip()
    Classification = request.POST.get('class', '').strip()
    # Still need purchase order, purchase date, purchase value, acquisition date, dept, mail exchange 
    PurchaseOrder = request.POST.get('porder', '').strip()
    PurchaseDate = request.POST.get('pdate', '').strip()
    PurchaseValue = request.POST.get('pvalue', '').strip()
    AcquistionDate = request.POST.get('aquidate', '').strip()
    Department = request.POST.get('dept', '').strip()
    MailExchange = request.POST.get('mex', '').strip()
    if equip:
        pval = PurchaseValue[1:len(PurchaseValue)]
        print("Purchase Value %s" % pval)
        if not equip.purchase_value:
            equip.purchase_value = pval
        if not equip.purchase_order:
            equip.purchase_order = PurchaseOrder
        if not equip.purchase_date:
            equip.purchase_date = PurchaseDate
        if not equip.acquisition_date: 
            equip.acquisition_date = AcquistionDate
        equip.dept = Department
        if not equip.mail_exchange:
            print("NAME FOR MAIL EXCHANGE")
            print(MailExchange)
            if MailExchange == "":
                print("NALLY")
            else:
                host = Hostname.objects.get(hostname=MailExchange)
                equip.mail_exchange = host
        equip.notes = Notes
        if not equip.cs_tag:
            equip.cs_tag = CSTag
        if not equip.vt_tag:
            equip.vt_tag = VTTag
        equip.description = Description
        if not equip.room:
            equip.room = Room
        equip.status = Status
        if not equip.serial_number:
            equip.serial_number = SerialNum
        equip.classification = Classification
        equip.save()
        print('New Notes: ')
        print(Notes)
        print('CSTag is: ')
        print(CSTag)
        print('VTTag is: ')
        print(VTTag)
        print('New description is: ')
        print(VTTag)
        newCommand = History()
        executor = '%s@vt.edu' % equip.custodian
        newCommand.command = "%s made changes to Equipment" % executor
        print(executor)
        newCommand.executor = executor
        newCommand.equipment = equip
        newCommand.save()
        host = Hostname.objects.filter(hostname=HostedName, building=equip.building, in_use=False)
        if len(host) > 0:
            print(host[0].building.name)
            if equip.hostname:
                if equip.hostname != host[0]:
                    equip.hostname.in_use = False
                    equip.hostname = host[0]
                    equip.hostname.save()
                    #messages.success(request, "Hostname Reassigned!")
                    messages.add_message(request, messages.SUCCESS, "Hostname Reassigned!")
                    # create new command stamp
                    newCommand = History()
                    newCommand.command = "Hostname Reassigned"
                    executor = '%s@vt.edu' % equip.custodian
                    print(executor)
                    newCommand.executor = executor
                    newCommand.equipment = equip
                    newCommand.save()
                else:
                  #  messages.success(request, "Hostname currently in use")
                    messages.add_message(request, messages.SUCCESS, "Hostname currently in use")
            else:

inventory/templates/inventory/addequipment.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'css/addequipment.css' %}" />
<link
  href="https://www.cssscript.com/demo/sticky.css"
  rel="stylesheet"
  type="text/css"
/>
<!-- Title -->
<h2
  class="d-flex justify-content-center align-items-center"
  style="font-size: 40pt"
>
  Add Equipment
</h2>
<form method="POST" style="padding: 60px">
  {% csrf_token %}
  <table class="table table-responsive">
    <thead>
      <tr>
        <th
          id="title"
          colspan="2"
          style="text-align: center; font-size: xx-large"
        >
          Details
        </th>
      </tr>
    </thead>
    <tbody>
      {% for field in EquipmentForm.visible_fields %}
      <tr>
        <td>{{field.label_tag}}</td>
        <td>{{field}}</td>
      </tr>
      {% if field.name == 'hostname' %}
      <tr>
        <td><label>IPv4:</label></td>
        <td><input id="id_ipv4" class="form-control" type="text" readonly></input></td>
      </tr>
      <tr>
        <td>IPv6:</td>
        <td><input id="id_ipv6" class="form-control" type="text" readonly></input></td>
      </tr>
      {% endif %} {% endfor %}
    </tbody>
  </table>
  <div style="text-align: center">
    <input type="submit" value="Submit" class="btn btn-outline-secondary" />
    <a href="/home/"
      ><button id="right-btn" class="btn btn-outline-secondary" type="button">
        Cancel
      </button></a
    >
  </div>
</form>

<script>

  document.getElementById("id_hostname").disabled = true;
  buildingSelect = document.getElementById("id_building");
  buildingSelect.addEventListener("change", function () {
    console.log(this.value);
    if (this.value != "") {
      document.getElementById("id_hostname").disabled = false;
    } else {
      document.getElementById("id_hostname").disabled = true;
    }
    document.getElementById("id_hostname").value = "";
    document.getElementById("id_ipv4").value = "";
    document.getElementById("id_ipv4").value = "";
  });

  hostnameSelect = document.getElementById("id_hostname");
  hostnameSelect.addEventListener("change", function () {
    if (this.value != "") {
      fetch('/addequipment')
        .then(function(response) {
          return response.json();
        })
        .then(function(data) {
          console.log(data);
        });
    }
    else {
      document.getElementById("id_ipv4").value = "";
      document.getElementById("id_ipv4").value = "";
    }
  });
</script>

{% endblock %}

inventory/templates/inventory/admin.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>
<script
  src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"
  type="text/javascript"
></script>

<!-- MDBootstrap Datatables  -->
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'mdb/css/addons/datatables.min.css' %}"
/>
<!-- MDBootstrap Datatables  -->
<script src="{% static 'mdb/js/addons/datatables.min.js' %}"></script>
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css"
/>
<!-- Title -->
<h1 class="d-flex justify-content-center align-items-center">Admin Page</h1>

<!-- Add User -->
<button
  type="button"
  class="btn btn-outline-secondary"
  data-toggle="modal"
  data-target="#addUserModal"
>
  <i class="bi bi-person-plus"></i>
  &nbsp; Add User
</button>

<!-- User Table -->
<div class="table-responsive">
  <table
    id="userTable"
    class="table table-bordered table-hover table-striped"
    style="width: 100%"
  >
    <thead>
      <tr>
        <th>PID</th>
        <th>Role Group</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for user in Users %}
      <tr>
        <th scope="row">{{ user.inventoryuser.pid }}</th>
        <td></td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.inventoryuser.phone_number }}</td>
        <td>
          <a
            href="#deleteConfirmationModal"
            type="button"
            class="btn btn-outline-secondary"
            data-toggle="modal"
            data-id={{ user.id }}
          >
            Delete
          </a>
          <a
            href="#editModal"
            type="button"
            class="btn btn-outline-secondary"
            data-toggle="modal"
            data-id={{ user.id }}
          >
            Edit
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<!-- Add User Modal Form -->
<div
  class="modal fade"
  id="addUserModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addUserModalLabel">Add User</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post">
        {% csrf_token %}
        <div class="modal-body">
          <table class="table table-responsive">
            <tbody>
              <tr>
                <td>{{ InventoryUserForm.pid.label_tag }}</td>
                <td>{{ InventoryUserForm.pid }}</td>
              </tr>
              <tr>
                <td>{{ UserForm.first_name.label_tag }}</td>
                <td>{{ UserForm.first_name }}</td>
              </tr>
              <tr>
                <td>{{ UserForm.last_name.label_tag }}</td>
                <td>{{ UserForm.last_name }}</td>
              </tr>
              <tr>
                <td>{{ InventoryUserForm.phone_number.label_tag }}</td>
                <td>{{ InventoryUserForm.phone_number }}</td>
              </tr>
              <tr>
                <td>{{ UserForm.email.label_tag }}</td>
                <td>{{ UserForm.email }}</td>
              </tr>
              <tr>
                <td>{{ UserForm.username.label_tag }}</td>
                <td>{{ UserForm.username }}</td>
              </tr>
              <tr>
                <td>{{ UserForm.password1.label_tag }}</td>
                <td>{{ UserForm.password1 }}</td>
              </tr>
              <tr>
                <td>{{ UserForm.password2.label_tag }}</td>
                <td>{{ UserForm.password2 }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>
          <input type="submit" value="Add User" class="btn btn-primary" />
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Delete Confirmation Modal -->
<div
  class="modal fade"
  id="deleteConfirmationModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addUserModalLabel">Delete Confirmation</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post">
      {% csrf_token %}
      <div class="modal-body">
        <input id="userID" name="userID" type="hidden" value=""/>
        <p>Are you sure you want to delete this user?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <input type="submit" value="Delete" class="btn btn-primary" />
      </div>
      </form>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    $("#userTable").DataTable();
    $(".dataTables_length").addClass("bs-select");
  });

  function deleteUser(userID) {
    $.ajax({
      url: '',
      type: 'DELETE',
      data: { id: userID,
              csrfmiddlewaretoken: document.querySelector('input[name="csrfmiddlewaretoken"]').value, 
            },
      contentType:'json',
      dataType: 'text',
    })
  }

  document.getElementById("deleteConfirmationModal").addEventListener("show.bs.modal", function(e) {
    document.getElementById("userID").value = e.relatedTarget.dataset.id
    console.log(e.relatedTarget.dataset.id)
  });
</script>
{% endblock %}

inventory/templates/inventory/button_change_template.html
{% extends “home.html” %}
{% load i18n %}
{% block submit_buttons_bottom %}
{{ block.super }}
<div class=”submit-row list-group”>
  <button type=”button” title=”Cancel” class=”list-group-item active” name=”_cancel” onclick=”location.href=’/admin/order/project/’;”>
    <span class=”glyphicon step-backward”></span>
    <span class=”text”>Cancel</span>
  </button>
</div>
{% endblock %}

inventory/templates/inventory/dashboard.html
{% load static %}

<!-- stuff -->

{% block extracss %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.24/b-1.7.0/r-2.2.7/sb-1.0.1/sp-1.2.2/datatables.min.css"/>
<link href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css"/>
{% endblock %}

<!-- Glucose Data Table -->

<table id="example2" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>PID</th>
                <th>Email</th>
                <th>Phone</th>
            </tr>
        </thead>
        <tbody>
            {% for user in Users %}
            <tr>
              <th scope="row">{{ user.first_name }}</th>
              <td>{{ user.last_name }}</td>
              <td>{{ user.email }}</td>
              <td>{{ user.phone }}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>

<!-- End Glucose Data Table -->

{% block extrajs %}

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.24/b-1.7.0/r-2.2.7/sb-1.0.1/sp-1.2.2/datatables.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/tables.js' %}"></script>

{% endblock %}

inventory/templates/inventory/home.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>
<script
  src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"
  type="text/javascript"
></script>

<!-- MDBootstrap Datatables  -->
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'mdb/css/addons/datatables.min.css' %}"
/>

<!-- MDBootstrap Datatables  -->
<script src="{% static 'mdb/js/addons/datatables.min.js' %}"></script>
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css"
/>

<!-- Title -->
<h1 class="d-flex justify-content-center align-items-center">Home</h1>

<!-- Add Equipment -->
{% if request.user.is_superuser %}
<a href="/addequipment" class="btn btn-outline-secondary" role="button">
  <i class="bi bi-plus-square"></i> &nbsp; Add Equipment</a
>
<a href="/home/DNS_Form/" class="btn btn-outline-secondary" role="button">
  <i class="bi bi-download"></i>
  &nbsp; Generate DNS Form</a
>
{% endif %}
<!-- Equipment Table-->
<div class="table-responsive">
  <table
    id="equipmentTable"
    class="table table-bordered table-hover table-striped"
    style="width: 100%"
  >
    <thead>
      <tr>
        <th>CS Tag</th>
        <th>Custodian</th>
        <th>Hostname</th>
        <th>Manufacturer/Model</th>
        <th>Building</th>
        <th>VT Tag</th>
        {% if request.user.is_superuser %}
        <th>Actions</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for equipment in equipments %}
      <tr>
        <th scope="row">{{ equipment.cs_tag }}</th>
        <td>{{ equipment.custodian }}</td>
        <td>{{ equipment.hostname.hostname }}</td>
        <td>{{ equipment.manufacturer_model }}</td>
        <td>{{ equipment.building.name }}</td>
        <td>{{ equipment.vt_tag }}</td>
        {% if request.user.is_superuser %}
        <td>
          <a href="/itemdetails/{{equipment.id}}/"
            ><button
              class="btn btn-outline-secondary"
              type="button"
              style="font-size: 14px; padding: 2px"
            >
              View
            </button></a
          >
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script>

  $(document).ready(function () {
    $("#equipmentTable").DataTable();
    $(".dataTables_length").addClass("bs-select");
  });
</script>
{% endblock %}